### ISSUE TITLE
hello, when i run the script, i got an error "SyntaxError: Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by xiatian12345** [szymonkaliski/openprocessing-scraper#1]
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request.post [as _callback] (/Users/xiazixi/Desktop/openprocessing-scraper/index.js:72:19)
    at Request.self.callback (/Users/xiazixi/Desktop/openprocessing-scraper/node_modules/_request@2.88.2@request/request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.<anonymous> (/Users/xiazixi/Desktop/openprocessing-scraper/node_modules/_request@2.88.2@request/request.js:1154:10)
    at Request.emit (events.js:193:13)
    at IncomingMessage.<anonymous> (/Users/xiazixi/Desktop/openprocessing-scraper/node_modules/_request@2.88.2@request/request.js:1076:12)
    at Object.onceWrapper (events.js:281:20)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)

could you help me?

**Comment by szymonkaliski** [comment]
I'm pretty sure openprocessing changed the way they handle their data in the last three years, this was a one-off project I needed back then, and I'm not supporting it anymore. Good luck!
